### ISSUE TITLE
Typedef warnings with Haxe 4.0.5

### ISSUE THREAD

**Issue by zommerfelds** [Jarrio/haxe-react-native-firebase#1]
Hi, I'm getting a bunch of warnings when compiling this library with Haxe 4.0.5

Example:
```
/home/gitpod/haxelib/js-firebase/0,2,0/firebase/database/Reference.hx:20: characters 53-69 : Warning : This typedef is deprecated in favor of js.lib.Promise<js.Promise.T>
```

**Comment by Jarrio** [comment]
I don't believe you're using my library, my library is not on haxelib nor is it versioned to 0.2.0. Either way that error can be fixed by just changing the code to the code it tells you to change it to

**Comment by zommerfelds** [comment]
@Jarrio wooops, so sorry, right yeah I wanted to post this in the other repo (done now https://github.com/okawa-h/js-firebase-extern/issues/1).

Maybe I should use your library instead :) The react native in the name made me scared it was not my use case, but maybe it's fine just for using Firebase.

Anyway apologies again and have a good day!

**Comment by Jarrio** [comment]
Yep, mine works for both. I just named the library when I was only focusing on rn. Although I haven't used it much recently so no idea if it still works or if the API has changed at all!
